version: '3.4'

services:
  ecommerce.api.customers:
    image: ${DOCKER_REGISTRY-}ecommerceapicustomers
    build:
      context: .
      dockerfile: ECommerce.Api.Customers\Dockerfile

  ecommerce.api.products:
    image: ${DOCKER_REGISTRY-}ecommerceapiproducts
    build:
      context: .
      dockerfile: ECommerce.Api.Products\Dockerfile


  ecomerce.api.orders:
    image: ${DOCKER_REGISTRY-}ecomerceapiorders
    build:
      context: .
      dockerfile: EComerce.Api.Orders\Dockerfile


  ecomerce.api.search:
    image: ${DOCKER_REGISTRY-}ecomerceapisearch
    build:
      context: .
      dockerfile: EComerce.Api.Search\Dockerfile

